---
name: Erro de formatação test
description: Algo está fora do lugar

labels:
  - formatting
  - triage

assignees: []

body:
  - type: markdown
    attributes:
      value: "## Thank you for contributing to our project!"
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report.
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: "A versão do manual pode ser encontrada na capa — ex: 2025"
      options:
        - 2025
      default: 0
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Versão
      description: "A versão do manual pode ser encontrada na capa — ex: 2025"
    validations:
      required: true
  - type: input
    id: chapter
    attributes:
      label: Capítulo
    validations:
      required: true
  - type: input
    id: pagina
    attributes:
      label: Página
    validations:
      required: true
  - type: textarea
    id: descricao
    attributes:
      label: Descrição
      description: Breve explicação ou comentário que ajude a localizar e entender o problema. Também
        podes adicionar capturas de ecrã
    validations:
      required: true
  - type: textarea
    id: sugestao
    attributes:
      label: Sugestão de correção
      description: Conteúdo depois de corrigido (opcional)
    validations:
      required: false
